spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lzslov123!

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false


