spring:
    datasource:
        url: jdbc:mysql://localhost:3306/news?serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: gyz
        password: gyz
my:
    scheduled:
        cron: 0 0 0,6,12,18 * * 1-7
#        cron: 0 0/1 * * * 1-7
swagger:
    enable: false
