spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bbs?serverTimezone=GMT%2B8
#        url: jdbc:mysql://39.100.50.227:11001/bbs?serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
#sql日志
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
my:
    scheduled:
        cron: 0 * * * * 1-7

swagger:
    enable: true

