#logging:
#  path: /log/
#  file: log.log

spring:
  profiles:
    active: dev
#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false

#    open-in-view: true
#懒加载
#spring.jpa.open-in-view=true
  mail:
    host: smtp.qq.com
    username: 355746803@qq.com
    password: uoyfucohfkozbgdc
    default-encoding: utf-8

server:
  port: 9090
  servlet:
    context-path: /


