spring:
    datasource:
        #url: jdbc:mysql://localhost:3306/bbs?serverTimezone=GMT%2B8
        url: jdbc:mysql://localhost:11001/bbs?serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: gyz
        password: gyz
